TransformerJoaoMiguel/Controllers/TipoTransformersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TransformerJoaoMiguel.Data;
using TransformerJoaoMiguel.Models;

namespace TransformerJoaoMiguel.Controllers
{
    public class TipoTransformersController : Controller
    {
        private readonly TransformerJoaoMiguelContext _context;

        public TipoTransformersController(TransformerJoaoMiguelContext context)
        {
            _context = context;
        }

        // GET: TipoTransformers
        public async Task<IActionResult> Index()
        {
              return _context.TipoTransformer != null ? 
                          View(await _context.TipoTransformer.ToListAsync()) :
                          Problem("Entity set 'TransformerJoaoMiguelContext.TipoTransformer'  is null.");
        }

        // GET: TipoTransformers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.TipoTransformer == null)
            {
                return NotFound();
            }

            var tipoTransformer = await _context.TipoTransformer
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tipoTransformer == null)
            {
                return NotFound();
            }

            return View(tipoTransformer);
        }

        // GET: TipoTransformers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TipoTransformers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Id")] TipoTransformer tipoTransformer)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tipoTransformer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tipoTransformer);
        }

        // GET: TipoTransformers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.TipoTransformer == null)
            {
                return NotFound();
            }

            var tipoTransformer = await _context.TipoTransformer.FindAsync(id);
            if (tipoTransformer == null)
            {
                return NotFound();
            }
            return View(tipoTransformer);
        }

        // POST: TipoTransformers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Name,Id")] TipoTransformer tipoTransformer)
        {
            if (id != tipoTransformer.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tipoTransformer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TipoTransformerExists(tipoTransformer.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tipoTransformer);
        }

        // GET: TipoTransformers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.TipoTransformer == null)
            {
                return NotFound();
            }

            var tipoTransformer = await _context.TipoTransformer
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tipoTransformer == null)
            {
                return NotFound();
            }

            return View(tipoTransformer);
        }

        // POST: TipoTransformers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.TipoTransformer == null)
            {
                return Problem("Entity set 'TransformerJoaoMiguelContext.TipoTransformer'  is null.");
            }
            var tipoTransformer = await _context.TipoTransformer.FindAsync(id);
            if (tipoTransformer != null)
            {
                _context.TipoTransformer.Remove(tipoTransformer);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TipoTransformerExists(int id)
        {
          return (_context.TipoTransformer?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

TransformerJoaoMiguel/Controllers/TransformersController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.ConstrainedExecution;
using System.Threading.Tasks;
using Azure.Storage.Blobs;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Blob;
using TransformerJoaoMiguel.Data;
using TransformerJoaoMiguel.Models;

namespace TransformerJoaoMiguel.Controllers
{
    public class TransformersController : Controller
    {
        private readonly TransformerJoaoMiguelContext _context;

        public TransformersController(TransformerJoaoMiguelContext context)
        {
            _context = context;
        }

        // GET: Transformers
        public async Task<IActionResult> Index()
        {
            var transformerJoaoMiguelContext = _context.Transformer.Include(t => t.TipoTransformer);
            return View(await transformerJoaoMiguelContext.ToListAsync());
        }

        // GET: Transformers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Transformer == null)
            {
                return NotFound();
            }

            var transformer = await _context.Transformer
                .Include(t => t.TipoTransformer)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (transformer == null)
            {
                return NotFound();
            }

            return View(transformer);
        }

        // GET: Transformers/Create
        public IActionResult Create()
        {
            ViewData["TipoTransformerId"] = new SelectList(_context.TipoTransformer, "Id", "Id");
            return View();
        }

        // POST: Transformers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Transformer transformer)
        {
            if (ModelState.IsValid)
            {
                if (transformer.FotoUpload != null && transformer.FotoUpload.Length > 0)
                {
                    transformer.Imagem = UploadImage(transformer.FotoUpload);
                }
                _context.Add(transformer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["TipoTransformerId"] = new SelectList(_context.TipoTransformer, "Id", "Id", transformer.TipoTransformerId);
            return View(transformer);
        }

        // GET: Transformers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Transformer == null)
            {
                return NotFound();
            }

            var transformer = await _context.Transformer.FindAsync(id);
            if (transformer == null)
            {
                return NotFound();
            }
            ViewData["TipoTransformerId"] = new SelectList(_context.TipoTransformer, "Id", "Id", transformer.TipoTransformerId);
            return View(transformer);
        }

        // POST: Transformers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Transformer transformer)
        {
            if (id != transformer.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (transformer.FotoUpload != null && transformer.FotoUpload.Length > 0)
                    {
                        DeleteImage(transformer.Imagem);

                        transformer.Imagem = UploadImage(transformer.FotoUpload);
                    }
                    _context.Update(transformer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TransformerExists(transformer.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["TipoTransformerId"] = new SelectList(_context.TipoTransformer, "Id", "Id", transformer.TipoTransformerId);
            return View(transformer);
        }

        // GET: Transformers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Transformer == null)
            {
                return NotFound();
            }

            var transformer = await _context.Transformer
                .Include(t => t.TipoTransformer)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (transformer == null)
            {
                return NotFound();
            }

            return View(transformer);
        }

        // POST: Transformers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Transformer == null)
            {
                return Problem("Entity set 'TransformerJoaoMiguelContext.Transformer'  is null.");
            }
            var transformer = await _context.Transformer.FindAsync(id);
            if (transformer != null)
            {
                DeleteImage(transformer.Imagem);
                _context.Transformer.Remove(transformer);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TransformerExists(int id)
        {
          return (_context.Transformer?.Any(e => e.Id == id)).GetValueOrDefault();
        }

        private string UploadImage(IFormFile file)
        {
            var nomeUnico = Guid.NewGuid().ToString() + "_" + file.FileName;
            var caminhoDestino = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/imagens", nomeUnico);


            if (!Directory.Exists(Path.GetDirectoryName(caminhoDestino)))
            {
                Directory.CreateDirectory(Path.GetDirectoryName(caminhoDestino));
            }

            using (var stream = new FileStream(caminhoDestino, FileMode.Create))
            {
                file.CopyTo(stream);
            }

            return "/imagens/" + nomeUnico;
        }
        private void DeleteImage(string caminhoImagem)
        {
            if (!string.IsNullOrEmpty(caminhoImagem))
            {
                var caminhoCompleto = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", caminhoImagem.TrimStart('/'));
                if (System.IO.File.Exists(caminhoCompleto))
                {
                    System.IO.File.Delete(caminhoCompleto);
                }
            }
        }
    }
}

TransformerJoaoMiguel/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TransformerJoaoMiguel</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TransformerJoaoMiguel.styles.css" asp-append-version="true" />
    <style>
        .parte-dinamica-footer{
           width: 100%;
           display: flex;
           justify-content: center;
           align-items: center;
        }

            .parte-dinamica-footer .img-fot-conteiner{
                  width: 50px;
                  height: 50px;
                  border-radius: 50%;
            }

            .parte-dinamica-footer .img-fot-conteiner img{
              width: 100%;
              height: 100%;
              object-fit: cover;
              border-radius: 50%;
            }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TransformerJoaoMiguel</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TipoTransformers" asp-action="Index">Tipo transformers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Transformers" asp-action="Index">Transformers</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <div class="parte-dinamica-footer">
                @{
                    var url = Context.Request.Path;
                }
                @switch (url.Value.ToLower())
                {
                    case "/" :
                        <div class="img-fot-conteiner">
                            <img class="imagem-footer-dinamico" src="https://olhardigital.com.br/wp-content/uploads/2023/04/Transformers-7.jpg" />
                        </div>
                        <p> - Home</p>
                        break;
                    case "/transformers/create":
                        <div class="img-fot-conteiner">
                            <img class="imagem-footer-dinamico" src="https://citeseriesefilmes.com.br/wp-content/uploads/2023/05/TF7_INTL_DGTL_TSR_IntlOptimusPrime_2025x3000_1SHT_OV-scaled-e1683829160552.webp" />
                        </div>
                        <p> - Create</p>
                        break;
                    case "/tipotransformers/create":
                        <div class="img-fot-conteiner">
                            <img class="imagem-footer-dinamico" src="https://citeseriesefilmes.com.br/wp-content/uploads/2023/05/TF7_INTL_DGTL_TSR_IntlOptimusPrime_2025x3000_1SHT_OV-scaled-e1683829160552.webp" />
                        </div>
                        <p> - Create</p>
                        break;
                    case "/transformers":
                        <div class="img-fot-conteiner">
                            <img class="imagem-footer-dinamico" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1SDwHd6ILXPhQMdIn213eQjUfeM0mEVZws5Y3EHgRVPtFBE7HkhSrplVnDAvWqXRivzU&usqp=CAU" />
                        </div>
                        <p> - Listagem</p>
                        break;
                    case "/tipotransformers":
                        <div class="img-fot-conteiner">
                            <img class="imagem-footer-dinamico" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1SDwHd6ILXPhQMdIn213eQjUfeM0mEVZws5Y3EHgRVPtFBE7HkhSrplVnDAvWqXRivzU&usqp=CAU" />
                        </div>
                        <p> - Listagem</p>
                        break;
                }
            </div>
            &copy; 2023 - TransformerJoaoMiguel - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>